-- MySQL Script generated by MySQL Workbench
-- Tue Aug 23 21:21:05 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8 ;
USE `agenda` ;

-- -----------------------------------------------------
-- Table `agenda`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`localidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agenda`.`tiposContacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`tiposContacto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agenda`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`personas` (
  `idPersona` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `fechaNac` DATETIME NOT NULL,
  `tipoContacto` INT(11) NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `altura` INT(11) NOT NULL,
  `piso` INT(11) NULL DEFAULT NULL,
  `depto` INT(11) NULL DEFAULT NULL,
  `localidad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `tipoContacto_idx` (`tipoContacto` ASC),
  INDEX `localidad_idx` (`localidad` ASC),
  CONSTRAINT `localidad`
    FOREIGN KEY (`localidad`)
    REFERENCES `agenda`.`localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipoContacto`
    FOREIGN KEY (`tipoContacto`)
    REFERENCES `agenda`.`tiposContacto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `agenda`.`localidades`
(`descripcion`)
VALUES
('Malvinas Argentinas');

INSERT INTO `agenda`.`localidades`
(`descripcion`)
VALUES
('Polvorines');

INSERT INTO `agenda`.`localidades`
(`descripcion`)
VALUES
('San Miguel');

INSERT INTO `agenda`.`tiposcontacto`
(`descripcion`)
VALUES
('Personal');

INSERT INTO `agenda`.`tiposcontacto`
(`descripcion`)
VALUES
('Trabajo');
